version: '2.4'
services:
    edgeai_8cwH3zaAWEwLPTB9XSHJNE_datasource:
        environment:
            ECCI_PUB_TARGETS: "{'feature-extraction': 'WbQFj3A6FhvHpWuJoBgYNL'}"
            ECCI_CONTAINER_TYPE: edge
            ECCI_APP_ID: 8cwH3zaAWEwLPTB9XSHJNE
            ECCI_CONTAINER_NAME: datasource
            ECCI_LOCAL_CONTAINERS: "['edgeai_8cwH3zaAWEwLPTB9XSHJNE_preprocess']"
            ECCI_LOCAL_BROKER_IP: 192.168.0.23
            ECCI_LOCAL_BROKER_PORT: 1888
            ECCI_LOCAL_BROKER_ID: WbQFj3A6FhvHpWuJoBgYNL
            ECCI_AGENT_ID: agent-id
            ECCI_APP_TYPE: controller
            ECCI_AGENT_IP: 192.168.0.23
        volumes:
            - ./main.py:/datasource/main.py
            - ./ecci_sdk.py:/datasource/ecci_sdk.py
        image: datasource:v1
        container_name: edgeai_8cwH3zaAWEwLPTB9XSHJNE_datasource
        restart: always